config/routes.rb
ExamplePhotouploader::Application.routes.draw do
  resources :photos

  get "home/index"

  devise_for :users,  :controllers => {:omniauth_callbacks => "omniauth_callbacks"} do
  delete 'signout', :to => 'sessions#destroy', :as => :destroy_user_session
  end

   root :to => 'home#index'

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
     attr_accessible :provider, :uuid
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  attr_accessible :title, :user_id, :image,:location, :lon,:lat

  geocoded_by :location, :latitude  => :lat, :longitude => :lon
after_validation :geocode, :if => :location_changed?

  mount_uploader :image, ImageUploader
 def mapped?
    if self.lat.blank? || self.lon.blank?
    false
    else
    true
    end
  end
  private
  def geocode_location

    photo_location = Geokit::Geocoders::GoogleGeocoder.geocode(self.location)

    if photo_location.success
    self.lat = photo_location.lat
    self.lon = photo_location.lng
    end

  end

 
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :authentications
  has_many :photos



  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :name
  
  
  def self.find_for_twitter_oauth(omniauth)
    authentication = Authentication.find_by_provider_and_uuid(omniauth['provider'], omniauth['uid'])

    data = omniauth.extra.raw_info

    if authentication && authentication.user
    authentication.user
    else

      user = User.create!(:username => data.nickname,:name => data.name)
      user.authentications.create!(:provider => omniauth['provider'], :uuid => omniauth['uid'])
    user.save
    user
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  @photos = Photo.order("created_at DESC").limit(6)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def twitter
    @user = User.find_for_twitter_oauth(env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Twitter'
      sign_in_and_redirect @user, event: :authentication
    else
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.failure', kind: 'Twitter', reason: 'User not found'
      redirect_to root_url
    end
  end
  
  def passthru
      render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authenticate_user!, :only=>[:create, :edit, :new, :destroy]
  # GET /photos
  # GET /photos.json
  def index
    if params[:search].present?
      @photos = Photo.near(params[:search], 10, :order => :distance)
    else
      @photos = Photo.all(:order =>"created_at DESC")
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])
    @photo.user = current_user
    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end
  
  def new
  end
  
  def destroy
    sign_out
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/home/index.html.erb
<ul>
<% @photos.each do |photo|%>
<%= render :partial=>"/photos/thumb", :locals => {:photo=>photo}%>
<% end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>example-photo-uploader</title>
		<meta name="viewport" content="width=device-width">
		<meta name="viewport" content="initial-scale=1.0">
		<%= yield :head %>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tag %>
	</head>
	<body>
		<div id="container">

			<div id="header">
				<div id="action_links">
					<% if user_signed_in? %>
					Hello, <%= current_user.name %> | <%= link_to('Signout', destroy_user_session_path, :method => 'delete') %>
					<% else %>
					<%= link_to image_tag('https://si0.twimg.com/images/dev/buttons/sign-in-with-twitter-l-sm.png', alt: 'Sign in with Twitter'), user_omniauth_authorize_path(:twitter), {:id => 'twitter_login'} %>
					<% end %>
				</div>
				<br/>
				<h1> <%= link_to("PHOTO UPLOADER", root_path)%></h1>
				<%= form_tag photos_path, :method => :get, :id=>"search" do %>
				<%= text_field_tag :search, params[:search], :html=>{:class=>"textfield"}  %>
				<%= submit_tag "Search Near", :name => nil %>
				<br/>
				<small> ex: London, Big Ben, Colombo </small>
				<% end %>
				<hr class="seperator" />
				<%=link_to "Home", root_path%> | <%=link_to "Photos", photos_path%>
			</div>

			<div id="content">
				<% flash.each do |name, msg| %>
						<div class="flash <%=name%>">
							
							<%= msg %>
						</div>
						<% end %>
				<%= yield %>
			</div>

			<div id="footer">

				<hr class="seperator" />
				&copy; Randika Rathugamage 2012.
			</div>
		</div>
	</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/_thumb.html.erb
<div id="multipleimages">
	<div class="thumb">
		<h3><%=photo.title%></h3>
		<small><%=photo.location%></small>
		<br/>
		<%=link_to image_tag(photo.image_url(:square)), photo_path(photo)%>
	</div>
</div>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>All photos</h1>
<div id="new-upload">
<%= link_to 'Upload', new_photo_path, :class=>"button orange" %>
</div>



<ul>
<% @photos.each do |photo|%>
<%= render :partial=>"/photos/thumb", :locals => {:photo=>photo}%>
<% end%>
</ul>


<div style="clear: both"></div>
<br />

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<h1><%=@photo.title%></h1>

<div id="imageHolder">
<%=image_tag(@photo.image_url(:medium))%>
</div>



<div id="sidebar">
<% if @photo.mapped?%>
<span> <%= image_tag "http://maps.google.com/maps/api/staticmap?size=200x200&sensor=false&zoom=16&markers=#{@photo.lat}%2C#{@photo.lon}" %> </span>
<br />
<strong><%=@photo.location%></strong><br />
lat/lon: <%=@photo.lat%>/<%=@photo.lon%>
<%end%>
<br />
<br />
<div id="photo-links">
<%= link_to 'Edit photo', edit_photo_path(@photo), :class=>"button orange" %>
</div>
</div>

<div style="clear: both"></div>